version: '3.7'
services:
  nginx:
    container_name: mastergas_nginx
    build: docker-images/nginx
    working_dir: /var/www/html
    command: nginx -g "daemon off;"
    ports:
      - "8055:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
  php:
    container_name: mastergas_php
    build: docker-images/php
    working_dir: /var/www/html
    command: php-fpm
    ports:
      - "9000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    container_name: mastergas_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: